/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios;

import Controlador.ControladorAdministracion;
import Modelos.Administrador;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import configuracion.Conexion;
import java.sql.Connection;


/**
 *
 * @author ALCIDES
 */
public class FormDatosAdmin extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormDatosAdmin
     */
    public FormDatosAdmin() {
        initComponents();
   jScrollPane1.setVisible(false);
jScrollPane3.setVisible(false);
jButton1.setVisible(false);
          
         ControladorAdministracion ca = new ControladorAdministracion();
    Administrador admin = ca.obtenerDatosAdministrador();
        if (admin != null) {
        jTextField2.setText(admin.getTelefono1()); // Teléfono 1
        jTextField3.setText(admin.getTelefono2()); // Teléfono 2
        jTextField4.setText(admin.getCelular());   // Celular
        jTextField5.setText(admin.getRutaImagenes()); // Ruta
        jTextField1.setText(admin.getMensaje());   // Mensaje
        
          
        ca.cambiacolor(this);
        ca.BotonesCrisitalPrim(jButton2, Color.green, Color.black, Color.black);
          ca.BotonesCrisitalPrim(jButton1, Color.red, Color.black, Color.black);
                  ca.BotonesCrisitalPrim(jButton3, Color.gray, Color.black, Color.black);
                  
                          Dimension d = new Dimension(100, 26); // El tamaño que quieras
      jButton3.setPreferredSize(new Dimension(26, 26)); 
         jButton3.setMinimumSize(new Dimension(26, 26)); 
         jButton3.setMaximumSize(new Dimension(26, 26));
         
           jButton2.setPreferredSize(d);
         jButton2.setMinimumSize(d);
         jButton2.setMaximumSize(d);
          
                  
           jButton1.setPreferredSize( new Dimension(100, 40)); //
         jButton1.setMinimumSize( new Dimension(100, 40)); //
         jButton1.setMaximumSize( new Dimension(100, 40)); //
         
             int anchoActual = this.getWidth();
    
    // Definimos el nuevo alto (por ejemplo, 500 píxeles)
    int nuevoAlto = 200; 
    
    // Aplicamos el cambio
    this.setSize(anchoActual, nuevoAlto);
    

  this.revalidate();
  this.repaint(); 
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jButton4 = new javax.swing.JButton();
        visor = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Mensaje:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, -1));

        jLabel3.setText("Telefono 1:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 40, -1, -1));

        jLabel4.setText("Telefono 2:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 66, -1, -1));

        jLabel5.setText("Celular:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 96, -1, -1));

        jLabel6.setText("Direccion:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 126, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 6, 393, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 36, 197, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 66, 197, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 96, 197, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 197, -1));

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 126, 142, -1));

        jButton3.setText("x");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 126, -1, -1));

        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 468, 47));

        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 40));

        jScrollPane3.setViewportView(jTextPane2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 210, 360, 40));

        jButton4.setText("FONDO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 49, 142, -1));
        getContentPane().add(visor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 130, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     Controlador.ControladorAdministracion ca = new ControladorAdministracion();
    jTextPane2.setText(ca.ejecutarSentencia(jTextPane1.getText()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   ControladorAdministracion ca = new ControladorAdministracion();
       String sql = "UPDATE administrador SET telefono1 = ?, telefono2 = ?, "
               + "celular = ?, ruta = ?, mensaje = ? WHERE id = 1;";

   
   ca.guardarConfiguracionEmpresa(jTextField2,jTextField3,jTextField4,jTextField5,jTextField1) ;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  // Obtenemos el ancho y alto actuales
    int anchoActual = this.getWidth();
    int altoActual = this.getHeight();
    
    // Definimos los dos estados
    int altoExpandido = 290;
    int altoContraido = 200; 

    if (altoActual != altoExpandido) {
        // --- CASO: AGRANDAR ---
        this.setSize(anchoActual, altoExpandido);
        
        jScrollPane1.setVisible(true);
        jScrollPane3.setVisible(true);
        jButton1.setVisible(true);
        
      
    } else {
        // --- CASO: ACHICAR ---
        this.setSize(anchoActual, altoContraido);
        
        jScrollPane1.setVisible(false);
        jScrollPane3.setVisible(false);
        jButton1.setVisible(false);
        
   
    }

    // Refrescar la interfaz
    this.revalidate();
    this.repaint();              // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                                    
    JFileChooser buscador = new JFileChooser();
    buscador.setFileFilter(new FileNameExtensionFilter("Imágenes", "jpg", "png", "jpeg"));
    
    if (buscador.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
        try {
            File origen = buscador.getSelectedFile();
            String nombreArchivo = origen.getName(); // Obtenemos el nombre (ej: "fondo.jpg")
            
            File carpetaDestino = new File("src/main/resources/main/Imagenes");
            if (!carpetaDestino.exists()) {
                carpetaDestino.mkdirs(); 
            }

            Path destino = Paths.get(carpetaDestino.getPath(), nombreArchivo);
            Files.copy(origen.toPath(), destino, StandardCopyOption.REPLACE_EXISTING);

            // --- NUEVO: GUARDAR EN BASE DE DATOS ---
          Conexion objetoConexion = new Conexion();
            String sql = "UPDATE administrador SET nombre_img = ? WHERE id = 1"; // Ajustá el ID si es necesario
            
try (Connection cn = objetoConexion.getConexion();
     PreparedStatement ps = cn.prepareStatement(sql)) {

    ps.setString(1, nombreArchivo);
    ps.executeUpdate();

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
}
            // ---------------------------------------

            // Mostrar en el JLabel
            ImageIcon foto = new ImageIcon(destino.toString());
            Image img = foto.getImage().getScaledInstance(visor.getWidth(), visor.getHeight(), Image.SCALE_SMOOTH);
            visor.setIcon(new ImageIcon(img));

            JOptionPane.showMessageDialog(null, "Imagen actualizada en carpeta y Base de Datos.");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }     // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JLabel visor;
    // End of variables declaration//GEN-END:variables
}
